### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by sandrobonazzola** [redhat-performance/phoronix-wrapper#16]
This project is missing licensing information.

**Comment by sandrobonazzola** [comment]
The included license state that the project is under GPL 2+ however a copy of https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt is missing within the repository and GitHub doesn't recognize the license (and possibly other automated tools as well).

I would recommend adding a copy of the license within the repo.

**Comment by dvalinrh** [comment]
License info added.

**Comment by dvalinrh** [comment]
Licensing information added.
